language: node_js

node_js:
  - 8
  - 10
  - 12

# Trigger build only when one of the following conditions is met
if: type = pull_request OR branch = master OR tag IS present

cache: npm

before_install:
  - docker-compose -f test-e2e/docker-compose.yml up -d

before_script:
  - ./scripts/cc-coverage-prepare.sh
  - npm install -g wait-on

script:
  - npm run lint
  - npm run lint:test
  - npm run test:report
  - npm run test:coveralls
  - npm run build
  - npm run install:local

  # E2E Acceptance tests
  - wait-on http://localhost:7200 -t 60000
  - (cd test-e2e/ && npm install && npm link graphdb && npm run test)

after_script:
  - ./scripts/cc-coverage-publish.sh

deploy:
  - provider: npm
    skip_cleanup: true
    email: graphdb-support@ontotext.com
    api_key: $NPM_TOKEN
    on:
      tags: true
      node_js: '12'

  - provider: pages
    skip_cleanup: true
    local_dir: ./docs
    github_token: $GITHUB_TOKEN
    on:
      branch: master
      node_js: '12'
